{{- if .Values.action.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "database-backup-s3.fullname" . }}
  labels:
    {{- include "database-backup-s3.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "database-backup-s3.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "database-backup-s3.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: "{{ .Values.action.restartPolicy }}"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if and .Values.configmap.enabled .Values.secrets.enabled }}
          envFrom:
          - configMapRef:
              name: {{ .Values.configmap.existingConfigMap | default (include "database-backup-s3.fullname" .) }}
          - secretRef:
              name: {{ .Values.secrets.existingSecret | default (include "database-backup-s3.fullname" .) }}
          {{- else if .Values.configmap.enabled }}
          envFrom:
          - configMapRef:
              name: {{ .Values.configmap.existingConfigMap | default (include "database-backup-s3.fullname" .) }}
          {{- else if .Values.secrets.enabled }}
          envFrom:
          - secretRef:
              name: {{ .Values.secrets.existingSecret | default (include "database-backup-s3.fullname" .) }}
          {{- end }}
          env:
          - name: SCHEDULE
            value: ''
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}          
          {{- if eq .Values.action.type "restore" }}
          command: 
          - sh
          - restore.sh
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
