{{- if and (.Values.secrets.enabled) (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database-backup-s3.fullname" . }}
  labels:
    {{- include "database-backup-s3.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $config := .Values.secrets.values }}
  {{ $name }}: {{ $config | b64enc | quote  }}
  {{- end }}
{{- end }}
