affinity: {}
envVarsConfigmap:
  enabled: true
  existingConfigMap: ''
  values:
    MAILRISE_DISCORD_DEFAULT_URI: discord://WEBHOOK_ID/WEBHOOK_TOKEN
filesConfigmap:
  enabled: true
  existingConfigMap: ''
  values:
    mailrise.conf: |
      #tls:
      #  mode: starttls
      #  certfile: /path/to/certificate.pem
      #  keyfile: /path/to/privatekey.pem

      smtp:
       auth:
         basic:
           username: !env_var SMTP_USERNAME
           AzureDiamond: !env_var SMTP_PASSWORD

      configs: 
        # Wildcard targets are evaluated in the order they appear in the
        # configuration file, and Mailrise uses the first match. So, this config
        # will catch any addresses not matched by the previous targets.
        #
        # Note that if you use "*" as your pattern, Mailrise will expand that to
        # "*@mailrise.xyz", which is probably not the catch-all target you wanted.
        #
        "*@*":
          urls:
            - !env_var MAILRISE_DISCORD_DEFAULT_URI
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: yoryan/mailrise
  tag: ''
imagePullSecrets: []
livenessProbe: ''
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe: ''
replicaCount: 1
resources: {}
secrets:
  enabled: true
  existingSecret: ''
  values:
    SMTP_PASSWORD: changeme
    SMTP_USERNAME: root
securityContext: {}
service:
  type: NodePort
  port: 8025
  nodePort: 30825
serviceAccount:
  annotations: {}
  automount: true
  create: false
  name: ''
tolerations: []
volumeMounts: []
volumes: []
verboseMode: true