affinity: {}
envVarsConfigmap:
  enabled: true
  existingConfigMap: ''
  values:
    TLS_MODE: "OFF"
filesConfigmap:
  enabled: true
  existingConfigMap: ''
  values:
    mailrise.conf: |
      tls:
         mode: !env_var TLS_MODE
      #  certfile: /path/to/certificate.pem
      #  keyfile: /path/to/privatekey.pem

      smtp:
        auth:
          basic:
            !env_var SMTP_USERNAME: !env_var SMTP_PASSWORD

      configs: 
        # Wildcard targets are evaluated in the order they appear in the
        # configuration file, and Mailrise uses the first match. So, this config
        # will catch any addresses not matched by the previous targets.
        #
        # Note that if you use "*" as your pattern, Mailrise will expand that to
        # "*@mailrise.xyz", which is probably not the catch-all target you wanted.
        #
        "*@*":
          urls:
            - !env_var MAILRISE_SLACK_DEFAULT_URI
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: yoryan/mailrise
  tag: ''
imagePullSecrets: []
livenessProbe: ''
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe: ''
replicaCount: 1
resources: {}
secrets:
  enabled: true
  existingSecret: ''
  values:
    SMTP_PASSWORD: changeme
    SMTP_USERNAME: username
    MAILRISE_SLACK_DEFAULT_URI: slack://T02FUKG2E/B07NX99HFPC/RG6huWnBGEZ0E2NMB0jb02V8/#general
securityContext: {}
service:
  nodePort: 30825
  port: 8025
  type: NodePort
serviceAccount:
  annotations: {}
  automount: true
  create: false
  name: ''
tolerations: []
verboseMode: false
volumeMounts: []
volumes: []