apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "mailrise.fullname" . }}-files"
  labels:
    {{- include "mailrise.labels" . | nindent 4 }}
data: 
  {{- range $name, $config := .Values.filesConfigmap.values }}
  {{ $name }}: {{ tpl $config $ | nindent 4 }}
  {{- end }}
