apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailrise.fullname" . }}
  labels:
    {{- include "mailrise.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: mail-port
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "mailrise.selectorLabels" . | nindent 4 }}
